FROM apache/airflow:2.9.1

# Passer en root pour installer des outils système si besoin (ex: git, gcc)
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Passer en utilisateur airflow
USER airflow

# Installer tes dépendances
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt